{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.138.782.0 (24.11)"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Cidades\",\"Água_recurso_2022_2023\",\"Copo_recurso_2022_2023\",\"sustentabilidade_-_copo_descartavel_2022\",\"Calendário\"]"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "sustentabilidade_-_copo_descartavel_2022",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Csv.Document(File.Contents(\"C:\\Users\\carva\\OneDrive\\Documentos\\GitHub\\PROJETO-UFU-SUSTENTABILIDADE\\dataset\\sustentabilidade_-_copo_descartavel_2022.csv\"),[Delimiter=\";\", Columns=6, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Cidade\", type text}, {\"Unidade\", type text}, {\"Tipo de Material\", type text}, {\"Ano\", Int64.Type}, {\"Mes\", type text}, {\"Pacote (100 un.)\", Int64.Type}}),",
          "    #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type\",{{\"Tipo de Material\", \"Tipo de Copo\"}, {\"Mes\", \"Mês\"}})",
          "in",
          "    #\"Renamed Columns\""
        ],
        "kind": "m",
        "lineageTag": "1087818e-7080-4821-a3cc-bf6a084755cc"
      }
    ],
    "relationships": [
      {
        "name": "AutoDetected_51d35374-045d-4b5c-8010-9c9d817da2f6",
        "fromColumn": "Cidade",
        "fromTable": "Água_recurso_2022_2023",
        "toColumn": "Cidade",
        "toTable": "Cidades"
      },
      {
        "name": "AutoDetected_e80a6354-cbcf-49da-a3ca-7e6a974ce0bb",
        "fromColumn": "Cidade",
        "fromTable": "Copo_recurso_2022_2023",
        "toColumn": "Cidade",
        "toTable": "Cidades"
      },
      {
        "name": "1fdc82fd-9863-2f95-d46d-f5c198155f13",
        "fromColumn": "Ano",
        "fromTable": "Copo_recurso_2022_2023",
        "toColumn": "Ano",
        "toTable": "Calendário"
      },
      {
        "name": "bd82122e-0fc5-4555-f372-46f5729804bb",
        "fromColumn": "Ano",
        "fromTable": "Água_recurso_2022_2023",
        "toColumn": "Ano",
        "toTable": "Calendário"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "Cidades",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Cidade",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1c373f8a-6b31-4e5b-8ed3-f08f02136e30",
            "sourceColumn": "Cidade",
            "summarizeBy": "none"
          },
          {
            "name": "ID_City",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1e9ad0ee-658b-433a-8104-83e8b45b996b",
            "sourceColumn": "ID_City",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "5fc29796-9516-461f-9058-44d3e8d869c0",
        "partitions": [
          {
            "name": "Cidades",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\carva\\OneDrive\\2.Studies\\Projetos\\SUSTENTABILIDADE UFU\\dataset\\basedados_2023_papel.csv\"),[Delimiter=\";\", Columns=7, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Cidade\", type text}, {\"Unidade\", type text}, {\"Ano\", Int64.Type}, {\"Mês\", type text}, {\"Quantidade\", Int64.Type}, {\"\", type text}, {\"_1\", type text}}),",
                "    #\"Removed Errors\" = Table.RemoveRowsWithErrors(#\"Changed Type\", {\"Ano\"}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Removed Errors\",\"to\",\"tão \",Replacer.ReplaceText,{\"Unidade\"}),",
                "    #\"Replaced Value1\" = Table.ReplaceValue(#\"Replaced Value\",\"ço\",\"ção \",Replacer.ReplaceText,{\"Unidade\"}),",
                "    #\"Replaced Value2\" = Table.ReplaceValue(#\"Replaced Value1\",\"so\",\"são\",Replacer.ReplaceText,{\"Unidade\"}),",
                "    #\"Replaced Value3\" = Table.ReplaceValue(#\"Replaced Value2\",\"Licitaçġes\",\"Licitações\",Replacer.ReplaceText,{\"Unidade\"}),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Replaced Value3\", each true),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Filtered Rows\",{\"Unidade\", \"Ano\", \"Mês\", \"Quantidade\", \"\", \"_1\"}),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Removed Columns\"),",
                "    #\"Duplicated Column\" = Table.DuplicateColumn(#\"Removed Duplicates\", \"Cidade\", \"Cidade - Copy\"),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Duplicated Column\",{{\"Cidade - Copy\", \"ID_City\"}}),",
                "    #\"Replaced Value4\" = Table.ReplaceValue(#\"Renamed Columns\",\"Uberlândia\",\"UDI\",Replacer.ReplaceText,{\"ID_City\"}),",
                "    #\"Replaced Value5\" = Table.ReplaceValue(#\"Replaced Value4\",\"Monte Carmelo\",\"MOO\",Replacer.ReplaceText,{\"ID_City\"}),",
                "    #\"Replaced Value6\" = Table.ReplaceValue(#\"Replaced Value5\",\"Patos de Minas\",\"SNPD\",Replacer.ReplaceText,{\"ID_City\"}),",
                "    #\"Replaced Value7\" = Table.ReplaceValue(#\"Replaced Value6\",\"Ituiutaba\",\"IUA\",Replacer.ReplaceText,{\"ID_City\"}),",
                "    #\"Replaced Value8\" = Table.ReplaceValue(#\"Replaced Value7\",\"SNPD\",\"PMS\",Replacer.ReplaceText,{\"ID_City\"})",
                "in",
                "    #\"Replaced Value8\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Água_recurso_2022_2023",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Cidade",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6050abe8-81c5-4194-9ae7-dd4695a51cd3",
            "sourceColumn": "Cidade",
            "summarizeBy": "none"
          },
          {
            "name": "Campus/Unidade",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a7213fd5-32d4-4586-a329-ed246d70b54d",
            "sourceColumn": "Campus/Unidade",
            "summarizeBy": "none"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cdb1100e-3cdd-4a92-a3a5-1416576eb5ab",
            "sourceColumn": "Mês",
            "summarizeBy": "none"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "79b566fa-8a86-4a91-9fac-da1b9c61bafd",
            "sourceColumn": "Ano",
            "summarizeBy": "none"
          },
          {
            "name": "Quantidade em m³",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "074777d3-6237-479b-8bbb-dfed1120169f",
            "sourceColumn": "Quantidade em m³",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "cde76a96-d929-4b95-90c5-11ed05949189",
        "partitions": [
          {
            "name": "Água_recurso_2022_2023",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\carva\\OneDrive\\Documentos\\GitHub\\PROJETO-UFU-SUSTENTABILIDADE\\dataset\\Água_recurso_2022_2023.csv\"),[Delimiter=\",\", Columns=5, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Cidade\", type text}, {\"Campus/Unidade\", type text}, {\"Mês\", type text}, {\"Ano\", Int64.Type}, {\"Quantidade em m³\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Copo_recurso_2022_2023",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Cidade",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5eeb3c97-7851-479b-9243-37a85a72c92f",
            "sourceColumn": "Cidade",
            "summarizeBy": "none"
          },
          {
            "name": "Unidade",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8d08e455-fdf0-4fdc-b6cf-0b12c90fb8cc",
            "sourceColumn": "Unidade",
            "summarizeBy": "none"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "079fca89-87f8-41ae-b996-ad86adce9755",
            "sourceColumn": "Ano",
            "summarizeBy": "none"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5add333d-31c1-42b1-a3f9-b403e43872cf",
            "sourceColumn": "Mês",
            "summarizeBy": "none"
          },
          {
            "name": "Tipo de Copo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "da6230dd-7811-440e-9c62-4540aad80be2",
            "sourceColumn": "Tipo de Copo",
            "summarizeBy": "none"
          },
          {
            "name": "Pacote (100 un.)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ed946876-d2a0-4719-bd60-b7479610d7ac",
            "sourceColumn": "Pacote (100 un.)",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "b6722fc1-2f13-4214-89b7-702cb1d8c9b1",
        "partitions": [
          {
            "name": "Copo_recurso_2022_2023",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\carva\\OneDrive\\Documentos\\GitHub\\PROJETO-UFU-SUSTENTABILIDADE\\dataset\\basedados_2023_copo.csv\"),[Delimiter=\";\", Columns=8, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Cidade\", type text}, {\"Unidade\", type text}, {\"Ano\", Int64.Type}, {\"Mês\", type text}, {\"Tipo de Copo\", type text}, {\"Quantidade\", Int64.Type}, {\"\", type text}, {\"_1\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"\", \"_1\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Columns\",{{\"Quantidade\", \"Pacote (100 un.)\"}}),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Renamed Columns\", each ([Tipo de Copo] = \"COPO PLASTICO DESCARTAVEL PARA AGUA  200 ML PACOTE COM 100\" or [Tipo de Copo] = \"COPO PLASTICO DESCARTAVEL PARA CAFÉ 50 ML PACOTE COM 100\")),",
                "    #\"Appended Query\" = Table.Combine({#\"Filtered Rows\", #\"sustentabilidade_-_copo_descartavel_2022\"}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Appended Query\",\"COPO PLASTICO DESCARTAVEL PARA AGUA  200 ML PACOTE COM 100\",\"Copo Descartável 200 ml\",Replacer.ReplaceText,{\"Tipo de Copo\"}),",
                "    #\"Replaced Value1\" = Table.ReplaceValue(#\"Replaced Value\",\"COPO PLASTICO DESCARTAVEL PARA CAFÉ 50 ML PACOTE COM 100\",\"Copo Descartável 50 ml\",Replacer.ReplaceText,{\"Tipo de Copo\"})",
                "in",
                "    #\"Replaced Value1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Calendário",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2ae6ecf5-ac55-4f65-b664-d38e00bd6cf1",
            "sourceColumn": "Ano",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "3ea63130-83ab-4fd7-83fd-6b100bc603a7",
        "partitions": [
          {
            "name": "Calendário",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WMjIwMlKK1QEzjJViYwE=\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", Int64.Type}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type\",{{\"Column1\", \"Ano\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}